#### 1. Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [1]:
import pandas as pd
import numpy as np

arr = pd.Series([2,3,4,5,6])
arr

0    2
1    3
2    4
3    5
4    6
dtype: int64

#### 2.Write a Python program to convert a Panda module Series to Python list and its type.

In [2]:
ser = pd.Series([5,6,7,8,9])
alist=ser.tolist()
print(alist)
type(alist)

[5, 6, 7, 8, 9]


list

#### 3.Write a Python program to add, subtract, multiple and divide two Pandas Series.

In [3]:
a = pd.Series([5,5,5,5])
b = pd.Series([1,2,3,4])

print("Add\n", a+b)
print("Subtract\n" , a-b)
print("Multiple\n" ,a*b)
print("Divide\n", a/b)

Add
 0    6
1    7
2    8
3    9
dtype: int64
Subtract
 0    4
1    3
2    2
3    1
dtype: int64
Multiple
 0     5
1    10
2    15
3    20
dtype: int64
Divide
 0    5.000000
1    2.500000
2    1.666667
3    1.250000
dtype: float64


#### 4 .Write a Python program to compare the elements of the two Pandas Series.

In [4]:
print(a>b)
print(a<b)
print(a==b)
print(a<=b)

0    True
1    True
2    True
3    True
dtype: bool
0    False
1    False
2    False
3    False
dtype: bool
0    False
1    False
2    False
3    False
dtype: bool
0    False
1    False
2    False
3    False
dtype: bool


#### 5.Write a Python program to create and display a Data Frame from a specified dictionary data which has the index labels

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James',
'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no',
'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [5]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

pd.DataFrame(data=exam_data,index=labels)

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

#### 6.Write a Python program to select the specified columns (score and attempts) and rows(1,3,5,6) from a given Data Frame.

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [6]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df_result = pd.DataFrame(data=exam_data,index=labels)
df_result[['score','attempts']].iloc[[1,3,5,6]]

score  attempts
b    9.0         3
d    NaN         3
f   20.0         3
g   14.5         1

#### 7.Write a Python program to select the rows the score is between 15 and 20 (inclusive).

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [7]:
df_result[df_result.score.between(15,20,inclusive=True)]

name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes

### 8. Write a Python program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [8]:
df_result[(df_result.attempts<2) & (df_result.score>15)]

name  score  attempts qualify
j  Jonas   19.0         1     yes

#### 9. Write a Python program to sort the data frame first by 'name' in descending order, then by 'score' in ascending order.

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [9]:
df_result.sort_values(by=['name','score'],ascending=[False,True])

name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes

#### 10. Write a Python program to insert a new column in existing Data Frame.

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [20]:
df_result['new_col']='Sample_'+df_result.index
df_result

name  score  attempts qualify   new_col
a  Anastasia   12.5         1     yes  Sample_a
b       Dima    9.0         3      no  Sample_b
c  Katherine   16.5         2     yes  Sample_c
d     Suresh    NaN         3      no  Sample_d
e      Emily    9.0         2      no  Sample_e
f    Michael   20.0         3     yes  Sample_f
g    Matthew   14.5         1     yes  Sample_g
h      Laura    NaN         1      no  Sample_h
i      Kevin    8.0         2      no  Sample_i
j      Jonas   19.0         1     yes  Sample_j
k     Robert   21.0         2     yes  Sample_k

#### 11.Write a Python program to change the name 'James' to 'Suresh' in name column of the data frame.

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']} labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [11]:
df_result[df_result.name=='James'].index

Index(['d'], dtype='object')

In [12]:
#df_result.name=df_result.name.replace('James','Suresh')

df_result.at[df_result[df_result.name=='James'].index,'name']='Suresh'

In [13]:
df_result

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d     Suresh    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Robert   21.0         2     yes